### ISSUE TITLE
get_encode_text fails in ScopusJournal

### ISSUE THREAD

**Issue by xaumex** [scopus-api/scopus#35]
Hi,
Running the example about ScopusJournal:
"""
from scopus.scopus_api import ScopusAbstract, ScopusJournal
ab = ScopusAbstract("2-s2.0-84930616647")
print(ScopusJournal(ab.issn))
"""

I get the following error:
Traceback (most recent call last):
  File "E:\Jaime\PAPELEO\Acreditacion\temp aneca CU\produccion 2017-06-19\prueba_journal.py", line 10, in <module>
    print(ScopusJournal(ab.issn))
  File "C:\Anaconda3\lib\site-packages\scopus\scopus_api.py", line 602, in __init__
    self.publisher = get_encoded_text(self.xml, 'entry/dc:publisher')
  File "C:\Anaconda3\lib\site-packages\scopus\utils\get_encoded_text.py", line 30, in get_encoded_text
    return container.find(xpath, ns).text
TypeError: slice indices must be integers or None or have an __index__ method

xml seems to be ok

The extrange think is that get_encode_text works fine in ScopusAbstract

**Comment by jkitchin** [comment]
That was a bug. I have pushed a fix for it.

**Comment by xaumex** [comment]
Now it works.
Thanks a lot

**Comment by jkitchin** [comment]
No problem.
