### ISSUE TITLE
Unable to create config file

### ISSUE THREAD

**Issue by rreka** [scopus-api/scopus#97]
Thanks for all your work on this module, it looks promising! I'm having an issue setting up the configuration file. After importing the module, and passing the config command, I receive an error.

```
>>> import scopus
C:\Users\XXXX\Anaconda3\lib\site-packages\scopus\utils\startup.py:17: UserWarning: scopus did not find a configuration file.  Please issue scopus.utils.create_config() to start the process which guides you through the generation of the configuration file or read https://scopus.readthedocs.io/en/stable/configuration.html.
  warnings.warn(text, UserWarning)
>>> scopus.utils.create_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\scopus\utils\create_config.py", line 11, in create_config
    file_exists = exists(CONFIG_FILE)
NameError: name 'exists' is not defined
>>>
```

Details:
Windows 10 (64 bit, v17763.437) 
scopus module v1.6.0

**Comment by Michael-E-Rose** [comment]
Sorry about that, my bad. It's fixed in the development versioin.

**Comment by rreka** [comment]
Thanks, that has fixed the name error. Looks like there is now a value error:

```
C:\Users\XXXX\Anaconda3\lib\site-packages\scopus\utils\startup.py:17: UserWarning: scopus did not find a configuration file.  Please issue scopus.utils.create_config() to start the process which guides you through the generation of the configuration file or read https://scopus.readthedocs.io/en/stable/configuration.html.
  warnings.warn(text, UserWarning)
>>> scopus.utils.create_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\scopus\utils\create_config.py", line 16, in create_config
    for key, value in DEFAULT_PATHS:
ValueError: too many values to unpack (expected 2)
>>> print(scopus.__version__)
1.6.1.dev1
>>>
```

**Comment by Michael-E-Rose** [comment]
Strange, I must have tested another version.  3e4eb31b8dcaa43d322e1167b01e44b05797b113 fixes the new bug.  Please check.

**Comment by rreka** [comment]
Just reinstalled the new dev version: it works! Thanks so much!
